const pairsString = `
GCAs,
JW Lane,
John Ryan,
Bill Doyle,
Andrew Hallacy,

Founding Class,
Jorge Nessi,,graduated,
Andrew Hallacy,,graduated,
Richard Benifield,,graduated,
Manoj Vangala,,graduated,
Ben Ceron,,graduated,
Brendan Nagle,,graduated,
Jimmy Leong,,graduated,
Scott Jones,,graduated,
Waylon Puckett,,graduated,
Bryan Sweat,,graduated,
Anthony Nishida,,graduated,
Scott Helmes,,graduated,
Mike Berlinger,,graduated,
Michael Burtt,,graduated,
JJ Netter,,graduated,
Jimmy Kepner,,graduated,
Harrison Carroll,,graduated,
Gwanyghaa Gana,,graduated,
Nick Gober,,graduated,
Steve Hooper,,graduated,
Galen Hughes,,graduated,
Brian Jo,,graduated,
Zach Markson,,graduated,
Thomas Marion,,graduated,
David Nelson,,graduated,
Coley Rahn,,graduated,
Son Tran,,graduated,
Yebo Bob Zhai,,graduated,
Jonathan Young,,graduated,
Kevin Shin,,graduated,
Adrian Bailey,,graduated,
Rajan Chaudhari,,graduated,
Jay Nonaka,,graduated,

Alpha Class,
Taka Chiba,Manoj Vangala,graduated,
Trevor Lindsay,Jimmy Kepner,graduated,
Alex Rodriguez,Jonathan Young,graduated,
Chris Tolosa,Mike Berlinger,graduated,
Soma Yamaoka,Michael Burtt,graduated,

Beta Class,
Mahdi Al Husseini,Rajan Chaudhari,graduated,
Nathan Daley,Trevor Lindsay,graduated,
William Herren,Richard Benifield,graduated,
Walter Holmes,Soma Yamaoka,graduated,
James Kane,Chris Tolosa,graduated,
Josh Netter,Coley Rahn,graduated,
Griffin Schmitt,Harrison Carroll,graduated,
Jarrett Stichler,Jay Nonaka,graduated,
Douglas Walker,Bryan Sweat,graduated,

Gamma Class,
Dean Park,Kevin Shin,graduated,
Richard Wang,Jarrett Stichler,graduated,
Benny Wu,Brendan Nagle,graduated,
John Xu,Douglas Walker,graduated,

Delta Class,
Austin Allen,Douglas Walker,graduated,
Nabeel Chhatriwala,Trevor Lindsay,graduated,
Alexander Detlefsen,Benny Wu,graduated,
Corey Fogg,William Herren,graduated,
Tomas Henriquez,Rajan Chaudhari,graduated,
Jack Li,Kevin Shin,graduated,
Ishaan Patel,Alex Rodriguez,graduated,
Bryce Rich,Andrew Hallacy,graduated,
Kane Ye,Nathan Daley,graduated,

Epsilon Class,
Mike Yan,Taka Chiba,graduated,
Ruo Zhang,Waylon Puckett,graduated,
Kyle Al Shafei,John Xu,graduated,
Jack Benedict,William Herren,graduated,

Zeta Class,
Grayson Noah,Scott Jones,graduated,
Nathan Lai,Jonathan Young,graduated,
Sudhanshu Ambadipudi,Harrison Carroll,graduated,
Clyde Nelson,Jarrett Stichler,graduated,
Davis Rider,Ishaan Patel,graduated,
Zach Hess,Bryce Rich,graduated,
Akash Doshi,Alex Rodriguez,graduated,
Yahia Ali,Jimmy Kepner,graduated,
Arjun Patra,Douglas Walker,graduated,
Robert Cooper,Austin Allen,graduated,
Chris Vanchev,Andrew Hallacy,graduated,
Andrew Pan,Corey Fogg,graduated,
Daniel Wang,Tomas Henriquez,graduated,

Eta Class,
Osama Ghani,Jonathan Young,graduated,
Stephen Kang,Taka Chiba,graduated,
Reid Clyburn,Andrew Hallacy,graduated,
Spencer Schiavo,Griffin Schmitt,graduated,
Dongju Lee,Bryce Rich,graduated,
Andrew Cameron,Ruo Zhang,graduated,

Theta Class,
Neel Atawala,Reid Clyburn,graduated,
Zack Mudge,Tomas Henriquez,graduated,
Matt Busch,Arjun Patra,graduated,
Grant Rohlfing,Robert Cooper,graduated,
Vineet Nadella,Bryce Rich,graduated,
Dalton Hutchison,Chris Vanchev,graduated,
Kai Sun,Kane Ye,graduated,

Iota Class,
Daniel Durham,Zach Hess,graduated,
Kristof Kovacs,Austin Allen,graduated,
Benjamin Lloyd,Grayson Noah,graduated,
Maxwell Sowatzka,Osama Ghani,graduated,
Michael Chan,Corey Fogg,graduated,
Collin Spencer,Andrew Pan,graduated,

Kappa Class,
Jake Meriwether,James Kane,graduated,
Kristopher Harris-Pitton,Spencer Schiavo,graduated,

Lambda Class,
Benjamin Garrison,Grant Rohlfing,graduated,
David Key,Zach Hess,graduated,
William Crawford,Osama Ghani,graduated,
Benjamin Blacklock,Dalton Hutchison,graduated,
Tucker von Holten,Tomas Henriquez,graduated,
Derek Higginbotham,Zack Mudge,graduated,
James Ellis,Matt Busch,graduated,
Jacob Present,Kristof Kovacs,graduated,
Daniel Blyakher,Maxwell Sowatzka,graduated,

Mu Class,
Jet Wang,Maxwell Sowatzka,graduated,
Sarthak Navjivan,Tucker von Holten,graduated,
Aman Jain,Osama Ghani,graduated,
Jason Lu,Dalton Hutchison,graduated,
Isaac Tomblin,Kristopher Harris-Pitton,graduated,
Ruarai O'Tighearnaigh,Matt Busch,graduated,
Zirui Wang,Jacob Present,graduated,
John Patrick Murphy,Dongju Lee,graduated,
John Kim,Jake Meriwether,graduated,
Yang Zhang,William Crawford,graduated,
Arnold Wang,Zach Hess,graduated,
Jacob Clayton,David Key,graduated,
Shivam Patel,Kristof Kovacs,graduated,
Minrui Liang,Collin Spencer,graduated,
Shaun Sharma,Zack Mudge,graduated,

Nu Class,
Justin Wurst,William Crawford,graduated,
Jacob Zhong,Jason Lu,graduated,
Gavin Goodier,David Key,graduated,
Winter Galyon,Shivam Patel,graduated,
Luke Xu,Maxwell Sowatzka,graduated,
Alexander Guguchev,Kristof Kovacs,graduated,

Xi Class,
Carter Kubes,Kristopher Harris-Pitton,graduated,
David Cheek,Zack Mudge,graduated,
Jacob Raymond Williams,David Key,graduated,
Justin Liang,Jason Lu,graduated,
Braxton Tomecek,Isaac Tomblin,graduated,
Maceo Cantu,Winter Galyon,,
Andrew Nazzari,Tucker von Holten,graduated,
Ryan Valuyev,Michael Chan,graduated,
Hung-Wei Lu,Jacob Zhong,graduated,
Nathan Zhu,Kristof Kovacs,graduated,
Rigved Goyal,Aman Jain,graduated,
Luke Gillette,John Patrick Murphy,,
Joseph Ni,Justin Wurst,graduated,
Terran Winner,Shaun Sharma,graduated,
Alec Helbling,Gavin Goodier,graduated,
Landon Menuey,Benjamin Garrison,graduated,
Ahmed Klasra,William Crawford,,
Sims Kuester,Jacob Present,graduated,
Bain McHale,Zach Hess,graduated,
Amarsaikhan Jargalsaikhan,Luke Xu,graduated,
Kevin Li,Shivam Patel,graduated,

Omicron Class,
Thomas Van Buren,Shivam Patel,,
JJ Miller,Michael Chan,graduated,
Edward Storey,Shaun Sharma,,
Liam Desai,Jacob Zhong,,
Andrew Osmond,Justin Wurst,graduated,
Yuji Takubo,Alexander Guguchev,graduated,
Harrison Euton,Kristopher Harris-Pitton,,
Tyler Bierfreund,Ryan Valuyev,graduated,
Akshat Nadella,John Patrick Murphy,graduated,
Nicholas Rivard,Carter Kubes,graduated,
Ishawn Gullapalli,Jacob Present,graduated,
Jackson Kjar,Joseph Ni,graduated,

Pi Class,
Nathan Wong,Thomas Van Buren,,
Beau Nunnally,Shivam Patel,,
Srikar Gadamsetty,Braxton Tomecek,,
Shane Werther,Andrew Nazzari,,
Shonjoy Bhattacharyya,Justin Wurst,,
Alex Pham,Alexander Guguchev,graduated,
Evan Lauer,Tyler Bierfreund,graduated,
Dave Claffey,Jacob Raymond Williams,,
Jackson McGill,Edward Storey,,
Chase Fletcher,Gavin Goodier,,

Rho Class,
Kian Kermani,Edward Storey,,
Brad Hornbeck,Braxton Tomecek,,
James Spittler,Andrew Nazzari,graduated,
Pranav Guntupalli,JJ Miller,,
Shantanu Velnati,Shivam Patel,,
George Pearson,Thomas Van Buren,,
Nicholas Gaug,Yuji Takubo,,
James Bevins,Beau Nunnally,,

Sigma Class,
Cooper Billsborough,Ahmed Klasra,graduated,
Adam Reitz,Braxton Tomecek,,
Andrew Shi,Nicholas Gaug,,
Mallesh Maharana,Shonjoy Bhattacharyya,,
William Bushey,Tyler Bierfreund,,
Arya Vajpayee,Rigved Goyal,,
Shalva Begiashvili,Yuji Takubo,,
Abhiram Bharatham,Akshat Nadella,,
Jason Lee,Shane Werther,,
Max Khanmamedov,Maceo Cantu,,
Nithik Balachandran,Shantanu Velnati,graduated,
Nathan Adair,Carter Kubes,,
Paul Hutchison,James Spittler,,
Kapish Potula,Srikar Gadamsetty,,
Riley Greene,Chase Fletcher,,

Tau Class,
Harshan Chenna,Cooper Billsborough,,
Suraj Karthic,Landon Menuey,,
Aayush Patel,George Pearson,,
Giovanni Hsu,Nathan Adair,,
Sivasai Manyapu,Harrison Euton,,

Upsilon Class,
Isaac Delgado,Mallesh Maharana,,
Adam Bakr,Paul Hutchison,,
Henry Moore,Nicholas Gaug,,
Kieran Kelleher,Shantanu Velnati,,
Pulkit Iyer,Shonjoy Bhattacharyya,,
Jay Nagpaul,Rigved Goyal,,
Liam Dolphin,Nathan Wong,,
Adwik Rahematpura,George Pearson,,
Nicholas Candello,JJ Miller,,
Tom Thayyil Thomas,Shalva Begiashvili,,
Ziyan Ishani,Harshan Chenna,,
Tate Barnard,Nathan Adair,,
James Wang,Andrew Shi,,

Phi Class,
Roland Kis,Mallesh Maharana,,
Ankith Keshireddy,Adam Bakr,,
Sohum Joshi,Harshan Chenna,,

Chi Class,
Michael Klikushin,transfer,,
`;
export { pairsString };